model = "l-deepseek-v4-flash"
model_provider = "openai"
model_reasoning_effort = "medium"
approval_policy = "on-request"
web_search = "live"

[model_providers.openai]
base_url = "http://10.136.128.2:58080/v1"
experimental_bearer_token = "sk-aaoLjZDkLppLDmeKd0SPEKWWP4inn56K8SsTnMuKNdGDJoVy"
wire_api = "chat"
requires_openai_auth = true

[model_providers.volcengine]
base_url = "https://ark.cn-beijing.volces.com/api/v3"
experimental_bearer_token = "633ef9cd-ef82-4311-9356-f4b99ec04150"
wire_api = "chat"
requires_openai_auth = false

[mcp_servers]

[hooks]
